### ISSUE TITLE
Support private mode

### ISSUE THREAD

**Issue by xMartin** [xMartin/grouptabs#125]
Currently the app doesn't start in Firefox and Safari private mode.

**Comment by jancborchardt** [comment]
An intermediate solution would be to let people know that this is the issue. Currently it’s only shown in the console log and it seems like the app does not work:
![screenshot from 2017-12-12 12-45-29](https://user-images.githubusercontent.com/925062/33883042-89acbd22-df3a-11e7-852f-87ee862f9721.png)

A simple sentence below the »Grouptabs« like »Currently the app does not work in private windows, please open it in normal browsing.« (And maybe switching to the Grouptabs logo instead of the loader.)

**Comment by xMartin** [comment]
In recent versions of Safari it works now!

Firefox is still having the problem (https://bugzilla.mozilla.org/show_bug.cgi?id=781982, https://github.com/pouchdb/pouchdb/issues/5641)

**Comment by xMartin** [comment]
The problem is that Firefox just doesn't provide IndexedDB in private mode. A good solution would be to use an in-memory database instead in this case. PouchDB has has an adapter for that. I am trying to get this working in our setup.
