### ISSUE TITLE
cannot input decimals on firefox on android

### ISSUE THREAD

**Issue by hugoroy** [xMartin/grouptabs#142]
Screenshots: https://pic.twitter.com/vbY5fi2CGF

When using Grouptabs on Android (Firefox 58), the keyboard to input numbers does not provide a way to enter a comma. So decimals can be entered with a dot.

Grouptabs will not accept decimals entered with a dot, and provides an error about fields not being complete (although all fields are complete, just one is not valid, therefore confusing users).

**Comment by hugoroy** [comment]
https://twitter.com/hugoroyd/status/971528459188129794

**Comment by xMartin** [comment]
Thanks for the report. Annoying HTML5 input types...

I have Firefox 58, German language on Android 6 and I am able to enter a comma. I wonder why it's not possible for you and if we can do anything except changing the input to normal text with the disadvantage of not providing the soft keyboard just for numbers.

As your browser is in French I assume you would prefer to enter comma, right? Or would you rather expect to have to use dots because the Grouptabs UI is in English?

**Comment by hugoroy** [comment]
I would expect a comma but if the keyboard only gives dot I  would put a dot without even thinking about it. Calculators in France use the dot instead of the comma to separate decimals...

I don't really know what to suggest here... the problem is I can see with some currencies that people could expect to enter dots to separate thousands and hundreds... 

Hard nut to crack 

Le 10 mars 2018 12:54:00 GMT+01:00, xMartin <notifications@github.com> a écrit :
>Thanks for the report. Annoying HTML5 input types...
>
>I have Firefox 58, German language on Android 6 and I am able to enter
>a comma. I wonder why it's not possible for you and if we can do
>anything except changing the input to normal text with the disadvantage
>of not providing the soft keyboard just for numbers.
>
>As your browser is in French I assume you would prefer to enter comma,
>right? Or would you rather expect to have to use dots because the
>Grouptabs UI is in English?

-- 
Envoyé de mon appareil mobile
Sent from my mobile device

**Comment by xMartin** [comment]
I realize this is not a Grouptabs bug (although the experience needs improvement) bug a Firefox/Android bug: This is the HTML of the input: `<input type="number" step="any" placeholder="0">`. If a comma is expected as decimal separator it should be available on the soft keyboard. Number parsing is not done by Grouptabs, it's native behavior.

**Comment by hugoroy** [comment]
It's not a bug, but it's a big issue for any Android French-locale user of Grouptabs. FYI, many people in France told me that Grouptabs didn't work, and I had no clue what the problem was (never got a proper bug report from them). I suspect that this could have been the issue…

I don't see any chances of this getting fixed in Android — I assume this is intended. People have been used to enter dots instead of comas to separate decimals (this is how it looks on calculators we used at school).

**Comment by xMartin** [comment]
It's just really weird because Firefox in French seems to require number inputs to use comma but then you get a keyboard with no comma. This cannot be intended.

Could you check in Chrome? What is your Android version? I changed my Android to French and still I can enter a comma in Firefox.

I will provide you with a set of possible workarounds that I'd like to ask you to test soon.

**Comment by hugoroy** [comment]
This seems fixed! I can put a coma now :-)

**Comment by xMartin** [comment]
Nice, thanks for the update! (I didn't change anything :) )
