### ISSUE TITLE
Feature request: Show who owes whom how much 

### ISSUE THREAD

**Issue by TanTrisGit** [xMartin/grouptabs#210]
I think it would greatly improve the user experience if there was a way of getting a suggestion like this:

Mark owes Adam $26
Lisa owes Adam $12
Lisa owes Mark $14

There would always be different possibilities for this of course, but in the end it does not matter. As long as GroupTabs suggests a way for everyone to pay their debts such that everyone gets the money they paid, it would be fine.

**Comment by xMartin** [comment]
Thank you so much for your input! I agree this would be a useful feature. So far I stayed away from it because, as you say, there's not one best way to settle a tab. But I agree, as suggestion could help without hurting.

We already have the issue #44 for this, so I'm going to close yours in favor of the previous one. Feel free to add more details how this feature could look like there. I will see if I find time to look into this again.
